### ISSUE TITLE
use .tex instead of text

### ISSUE THREAD

**Issue by reox** [Metalab/Statuten#1]
There is a .tex file here: https://metalab.at/wiki/Datei:Metalab_statuten.tex

**Comment by metachris** [comment]
direct link: https://metalab.at/wiki/images/8/8d/Metalab_statuten.tex

Ich wäre für Markdown, but text does the job as well.

**Comment by MacLemon** [comment]
There's no .tex in here for a purpose. The idea is to provide an easily and Human readable diff of Change suggestions for the general assembly on Monday. There is no benefit in TeX or MarkDown for that purpose and for a text with a life expectancy of less than 24 hours.

**Comment by keikoro** [comment]
I'd suggest keeping the plain text version as it's the one format that's easily readable by most everyone, including "non-technical" folks.

For those who want to have a `.tex` version which allows for fancily formatted PDFs (which are nice, I agree): maybe there's a plugin that allows extracting the actual text to a `.txt` file?

**Comment by keikoro** [comment]
Oups, commenting late.

@MacLemon is the repo going to get deleted again after the general assembly? (Why though?)

**Comment by reox** [comment]
okay, sorry i thought you wanted to move the statuten from the wiki. never mind the issue!
