### ISSUE TITLE
Remove push abilities for all peple in Metalab

### ISSUE THREAD

**Issue by reox** [Metalab/Statuten#12]
If this repo should contain a valid version of the statuten, I would remove push access for all members. I wanted to create a pull request and pushed accidentily into the wrong remote...

**Comment by burnoutberni** [comment]
I just activated branch protection for the master branch, so "all commits must be made to a non-protected branch and submitted via a pull request with at least one approved review and no changes requested before it can be merged into master." There could still be malicious statute changes now, but at least they don't happen on accident. One could also restrict pushing to the master branch to e.g. the board, but I think this is good enough.
