### ISSUE TITLE
Zettelwahl / geheime Wahl

### ISSUE THREAD

**Issue by phaer** [Metalab/Statuten#9]
**tl;dr:** Ich möchte einen Wahlmodus der möglichen Gruppenzwang bei Entscheidungen schon im Ansatz verhindert. Glaube dass das einer von vielen Ansätzen ist, Diskussionen auf Dauer angenehmer zu halten. Modus in etwa wie https://metalab.at/wiki/Generalversammlung/Zettelwahl

----

Das Metalab ist mit all seinen Membern mitlerweile ein recht komplexes soziales Gefüge. Es gibt verschiedenste Nutzer\*innen-Gruppen die sich z.T. kaum gegenseitig kennen und mitunter recht verschiedene Vorstellungen davon haben was Raum und Verein tun sollen und können.

Diese Diversität halte ich ansich eher für eine Stärke, als für eine Schwäche, sie birgt aber auch ein paar Risiken. Eines davon ist eine mögliche Fraktionierung, die dazu führt dass Konflikte und Ideen weniger sachlich besprochen werden und mehr als Machtkampf zwischen verschiedenen Gruppen verstanden werden. Ich persönlich halte Teile der GV 2016 und der nachfolgenden Diskussionen für ein Symptom eines solchen Prozesses. 

Für einen offenen und vielfältigen Verein ist sowas sozial und kulturell gesehen auf Dauer Gift, weil es unvoreingenommene Diskussionen erschwert und das gegenseitige Vertrauen untergraben kann. Ansätze sowas zu vermeiden gibt - und braucht - es sicher viele, u.a. in der Form in der wir Diskussionen führen (vgl. GV 2016 mit nachfolgendem "Reden"-Termin).

Ein Ansatz zumindest die Symptome zu lindern ist eine geheime Wahl mittels Abstimmung per Zettel. Sie kann erheblich dazu beitragen möglichen Peer Pressure in kontroverseren Diskussionen zu mindern und somit hoffentlich zu nuancierteren Debatten statt Frontstellungen beitragen. Und sie erlaubt gerade auch neueren Mitgliedern sich einfacher einzubringen ohne Gefahr zu laufen sich bei umstrittenen Themen in Konflikte zu verstricken, die sie vielleicht noch gar nicht kennen.

Forderungen nach einem solchen Wahlmodus gab es in der Geschichte des Metalabs bereits wiederholt, bisher scheiterte es meines Wissens vor allem an mangelnder Vorbereitung einer geheimen Wahl und weniger an inhaltlichen Bedenken. Ich bitte zu ergänzen wenn es sachliche Gegenargumente gibt.

Andernfalls würde ich mich gerne an einer Vorbereitung einer solchen Wahl beteiligen und gemeinsam mit euch eine Statuten-Änderung erarbeiten, die eine geheime Wahl zum regulären Modus für Beschlüsse der Generalversammlung macht. Auf den ersten Blick scheint mir der [Vorschlag von Vierlex im Metalab-Wiki 2013](https://metalab.at/wiki/Generalversammlung/Zettelwahl) immer noch zeitgemäß, weshalb ich ihn hier mal, bearbeitet, kopiere. Aber wir könnens natürlich gern noch anpassen ;)

> # Wahlmodus
> * 6 Durchgänge (für je Obperson, Schriftführer\*in, Kassier\*in und Stellvertreter\*innen)
> * für jeden Durchgang eigene Zettel, also insgesamt 6 verschiedene Zettel.
> * durchnummerierte Zettel mit den Wahlmöglichkeiten werden 2 Tage vor der GV gedruckt.
> * Zettel werden am Anfang der GV verteilt und auf dem Presentertisch vorne aufgelegt mit 2 
> Freiwilligen + Vorstand die kontrollieren ob sich eh jeder nur einen Zettel pro Durchgang und Stimme > - also `6 * (1 + Anzahl der übertragenen Stimmen)` - nimmt und auch die Anzahl der Stimmen zählt, die dann mit der durchlaufenden Nummer der übrigen Zettel verglichen wird.
> * Nicht abgegebene Zettel gelten als Enthaltung - es gibt aber auch am Zettel selber die Option um anonyme Enthaltungen zu ermöglichen. 
> Die Zettel werden von 2 Freiwilligen ausgewertet, erster macht die Zettel auf und sagts der Zweiten, Zweite nimmt den Zettel, prüft und legt ihn auf den Stapel der gewählten Person.

Eine Frage dabei wäre, wie wir mit Anträgen jenseits der Vorstandswahl umgehen. Noch mehr Zettel? Oder reicht ein Zettel für alles? Oder ein Zettel für Leute, einer für Statuten?

Macht das Sinn? Ist das blöd? Übersehe ich was? Ich bitte um angeregte Diskussion :)

**Comment by rponline** [comment]
Grundsätzlich finde ich geheime Wahlen toll, ich würde sie etwas anders implementieren.

* Ein Zettel (oder maximal zwei) für alles sollte reichen. Wenn man es wirklich ernst nimmt, macht man für jede Wahl eigene Stimmzetteln. Aber das wäre mMn. Overkill fürs Lab.
* Einwurf der Stimmzetteln protokollieren, und maximal erst beim Auszählen nummerieren.
* Bei mehr als einer Option die Schulze-Methode anwenden weil sie mMn am fairsten ist. (die genaue Variante weiß ich noch nicht, aber wir sollten das genau definieren um Streitigkeiten vorzubeugen)
* Den Wahlmodus nicht so genau in die Statuten reinschreiben sondern einfach eine Wahlordnung erstellen, welche am Anfang der GV abgestimmt wird oder in Zukunft von den Statuten referenziert wird. Das hat den Vorteil, dass man diese Ordnung dann auch ohne polizeilicher Bestätigung ändern kann.

ich hab hier mal einen relativ pragmatischen, geheimen Wahlprozess skizziert:

> *   Vor der Generalversammlung
>     *   Wahlhelfer/innen organisieren (ca. 4)
>         *   Diese könnte man ggf. noch von der Generalversammlung am Anfang wählen lassen.
>     *   Wahlurne besorgen
>     *   Sich um „Wahlkabinen“ kümmern. (man kann auch einfach den Scannerraum etc. verwenden)
>     *   Genug Kugelschreiber, Kopierpapier und formgleiche Kuverts besorgen
>     *   Stimmzettel so weit wie möglich vorbereiten (ich hätte schon ein Grundgerüst)
>     *   Drucker testen
>     *   Liste mit stimmberechtigten Mitgliedern vorbereiten und ausdrucken
> *   Nach der Kandidatur-Deadline (während der GV)
>     *   Stimmzettel fertigstellen (Testdruck!)
>     *   Genug Stimmzetteln ausdrucken (+ ~5% extra)
> *   Abstimmung
>     *   Stimmzetteln und Kuverts werden einfach verteilt. Wir gehen davon aus, dass alle Personen im Raum wissen ob sie wahlberechtigt sind. Die Überprüfung erfolgt später.
>     *   Mitglieder müssen den Zettel unbeobachtet ausfüllen/bearbeiten und in das Kuvert geben.
> *   Einwurf der Stimmzettel
>     *   Leere Wahlurne wird präsentiert
>     *   Mitglieder stellen sich für den Einwurf an
>     *   Mitglied sagt Name
>     *   Ein/e Wahlhelfer/in prüft nach Wahlberechtgung (sucht den Namen in der Liste) und hakt diesen ab. Dieser Vorgang wird von anderen Wahlhelfer/innen beobachtet.
>     *   Mitglied wirft den Zettel unter Beobachtung von Wahlherlfer/innen in die Wahlurne ein.
> *   Auszählung der Stimmen
>     *   Wahlhelfer/In zählt die Kuverts durch.
>     *   Anzahl der abgegebenen Kuverts wird durch Wahlhelfer/innen bekannt gegeben und protokolliert. Weites wird die Anzahl mit der Liste abgeglichen. Wenn diese nicht übereinstimmt muss die Wahl wiederholt werden.
>     *   Die Kuverts werden geöffnet und die Stimmzetteln werden rausgegeben. Es wird überprüft ob die Anzahl der Zetteln im Kuvert vom Soll abweicht. Wenn mehr Zetteln als vorgesehen drinnen sind, ist die Stimme ungültig. Irregularitäten werden protokolliert. Fehlende Stimmzetteln werden als ungültig gewertet.
>     *   Wahlhelfer/innen übertragen die Wahlergebnisse in eine Datei, mit der man die Ergebnisse ausrechnen lassen kann.
>         *   Wer bekommt diese Datei noch? Veröffentlichen?
> *   Die Gewinner der Wahl werden bekannt gegeben. Diese müssen ihre Wahl noch annehmen.

**Comment by burnoutberni** [comment]
> Ein/e Wahlhelfer/in prüft nach Wahlberechtgung (sucht den Namen in der Liste) und hakt diesen ab. Dieser Vorgang wird von anderen Wahlhelfer/innen beobachtet.

Den Punkt würd ich gleich am Anfang der Generalversammlung abhaken und Stimmkarten austeilen (durch die Anzahl der Stimmkarten können dann Stimmübertragungen mitgeregelt werden). Die Stimmkarten können dann für Abstimmungen per Handzeichen verwendet werden (und eigentlich müsste ja für die auch schon die Stimmberechtigung festgestellt sein).
Zusätzlich wird beim Austeilen der Stimmzettel eine Markierung auf der Stimmkarte geschrieben (z.B. eine fortlaufende Nummer pro Wahlgang) und beim Einwerfen der Stimmkarte in die Urne abgehakt. Damit ist sicher gestellt, dass ein stimmberechtigtes Mitglied genau einen Stimmzettel einwirft (bzw. bei Stimmübertragungen genau dasselbe nur mit mehreren Stimmkarten und Stimmzetteln) und es muss nicht bei jedem Wahlgang die Stimmberechtigung festgestellt werden.

Schulze++, muss aber gut vorher erklärt werden. Außerdem stellt sich die Frage, ob Schulze mit Akzeptanzwahl in einem Schritt oder eine getrennte Akzeptanzwahl vorher oder ob auf eine Akzeptanzwahl verzichtet wird.

**Comment by rponline** [comment]
Ich würde gerne versuchen, das alles auf einen Wahlgang zu beschränken und den Vorgang möglichst unbürokratisch zu halten. Deshalb auch nur die Überprüfung der Wahlberechtigung beim Einwurf.

Falls ich da aber wirklich wichtige Dinge übersehe, welche die Integrität der Wahl stark negativ beeinflussen, dann sagt mir das bitte :)

Aber du hast recht, eine Akkreditierung ist sowieso notwendig um generell abstimmen zu können. Vllt sind Stimmkarten gar nicht mal so eine blöde Idee.

**Comment by telerainbow** [comment]
Ein einfacher Textbaustein ([hier](http://www.ocg.at/de/statuten) abgeschrieben):

> Abstimmungen und Wahlen werden in offener Wahl vorgenommen. Auf Verlangen eines anwesenden Mitgliedes muß in geheimer Wahl mittels Stimmzettel [insert Wahlmodus here] abgestimmt werden.

Sollte vll. noch um die Art der geheimen Wahl ausgeweitet werden.

Dass die geheime Wahl ein Minderheitenrecht sein muss sollte eigentlich eh klar sein, letztes Jahr hat ja leider die Mehrheit eine geheime Wahl abgelehnt.

**Comment by rponline** [comment]
@telerainbow Finde ich gut.
Bitte mach daraus einen abstimmbaren Statutenänderungsantrag.

**Comment by burnoutberni** [comment]
Siehe #10 für Vorschlag zur Statutenänderung

**Comment by telerainbow** [comment]
> Sich um „Wahlkabinen“ kümmern. (man kann auch einfach den Scannerraum etc. verwenden)

Ich schlage die Telefonzelle vor, mit einem Vorhang als Sichtschutz.

**Comment by telerainbow** [comment]
Ein weiterer Vorschlag zum Wahlmodus, **zur Diskussion**

Vor der GV wird die Stimmberechtigung geprüft und n+m nummerierte [0..n+m] kleine Zettel ausgehändigt (n ... erwartete Anzahl an Abstimmungen, m ... Überhang für unerwartete Anträge). Die Zettel sind auf keine Weise einem Mitglied zuzuordnen, aber "fälschungssicher" (z.B. Stempel). In der Wahlkabine stehen j+1 verschiedene Urnen die ebenfalls nummeriert sind (j ... Anzahl der Optionen bei dieser Abstimmung , +1 für Enthaltung).
Wird eine geheime Wahl verlangt, wird durch die Wahlkommission die Nummer des aktuellen Wahlgangs ausgerufen und die Optionen den Urnen zugeordnet (z.B.: Django Müller: Urne 0, Metelab Gerhard: Urne 1, Enthaltung: Urne 2). Der Zettel mit der Nummer des Wahlgangs wird dann von jeder abstimmenden Person in eine der j+1 Urnen abgegeben.

Opinions?

**Comment by rponline** [comment]
> Ein weiterer Vorschlag zum Wahlmodus, zur Diskussion

Ich schätze mal, in diesem Rahmen wär's zwar nicht so akut, aber generell ermöglichst du mit dieser Technik den Stimmenkauf (eine Person kann die Stimme einer anderen Person abkaufen, stehlen, etc.).
Ich würde es deshalb lieber nicht machen.

**Comment by burnoutberni** [comment]
> Ich schätze mal, in diesem Rahmen wär's zwar nicht so akut, aber generell ermöglichst du mit dieser Technik den Stimmenkauf (eine Person kann die Stimme einer anderen Person abkaufen, stehlen, etc.).

Das geht ja sowieso, wir haben ja auch Stimmübertragungen mit denen Stimmen akkumuliert werden können.

> Vor der GV wird die Stimmberechtigung geprüft und n+m nummerierte [0..n+m] kleine Zettel ausgehändigt 

Ich kenn das von den Generalversammlungen einer deutschen Kleinpartei mit mehreren 1000 Teilnehmer*innen, da werden vorgedruckte farblich kodierte Stimmzettelblöcke ausgeteilt, die rund zwei dutzend durchnummerierte Ja/Nein/Enthaltung-Felder haben, damit alle möglichen Abstimmung spontan per Papierwahl durchgefüllt werden können. For our purpose overkill, IMHO.

> Wird eine geheime Wahl verlangt, wird durch die Wahlkommission die Nummer des aktuellen Wahlgangs ausgerufen und die Optionen den Urnen zugeordnet (z.B.: Django Müller: Urne 0, Metelab Gerhard: Urne 1, Enthaltung: Urne 2). Der Zettel mit der Nummer des Wahlgangs wird dann von jeder abstimmenden Person in eine der j+1 Urnen abgegeben.

Das ist gar nicht so effizient, wie du dir das vorstellst, macht es komplizierter die leeren Urnen herzuzeigen und – am wichtigsten – zwingt uns dazu ein Wahlverfahren zu verwenden, wo du nur einer Person eine Stimme geben kannst. Ich bin stark für irgendeine Form von Reihungswahl am liebsten Schulze, alternativ auch IRV.

**Comment by phaer** [comment]
Bitte wieder öffnen oder einen neuen Issue anlegen, falls jemand diese Diskussion nochmal beginnen möchte. Ich ja nicht ;)
